# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ release ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITcreative_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: openjdk-17-jre wget
          version: 1.0

      # Runs a single command using the runners shell
      - name: Set up Pack
        run: |
          mkdir -p working/{pack,complete/pack}
          cd working/pack || exit

          rsync -a ../../assets assets
          cp ../../pack.mcmeta pack.mcmeta
          
          zip -r boxsmppack.zip assets pack.mcmeta
          cd ../../
         
      - name: Set up Resource Pack Converter
        run: |
          mv working/pack/boxsmppack.zip working/complete/boxsmppack.zip
          mkdir -p working/convert/template
          cp working/complete/*.zip working/convert/template
          wget https://github.com/agentdid127/ResourcePackConverter/releases/download/2.2.6/ResourcePackConverter.jar
          mv ResourcePackConverter.jar ResourcePackConverter-Console-2.2.6.jar
  
     # - name: Convert Packs
     #   run: |
     #     cp -r working/convert/template working/convert/1_21_7
     #     cd working/convert/1_21_7/
     #     java -jar ../../../ResourcePackConverter-Console-*.jar --from 1.21.7 --to 1.21.8 --minify
     #     rm hubpack.zip
     #     rm creativepack.zip
     #     mv hubpack_converted.zip ../../complete/hubpack-1.21.7.zip
     #     mv creativepack_converted.zip ../../complete/creativepack-1.21.7.zip
     #     cd ../../../
          
      - name: Set up targets
        run: |
          mv working/complete .
          rm -rf working
          rm -f ResourcePackConverter-*.jar

          echo 'VERSION='$(cat version.txt) >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            Release Automatically Generated by software... Please change draft to add changelog.
          draft: true
          prerelease: false

      - name: Upload Pack Release for 1.21.8
        id: upload-pack-release-1_21_8
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./complete/boxsmppack.zip
          asset_name: boxsmppack-1.21.8.zip
          asset_content_type: application/zip