# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ release ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITcreative_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Set up Pack
        run: |
          zip -r boxsmppack.zip assets pack.mcmeta
          echo 'VERSION='$(cat version.txt) >> $GITHUB_ENV
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
          file: boxsmppack.zip
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
